### ISSUE TITLE
Multiple pagy in one page will caused wrong page param updated and own page number becomes MARKER

### ISSUE THREAD

**Issue by vshy108** [ddnexus/pagy#143]
If second page of the second pagy_nav with page_param of page_published in same page will have link with **params page=2&page_published=-pagy-281379437229102211-** . 

`<a href="/blogs?page=2&amp;page_published=-pagy-281379437229102211-" class="page-link" rel="next">2</a>`

which should be 

`<a href="/blogs?page_published=2" class="page-link" rel="next">2</a>`

I tried Pagy.init(elementWrapPagyNav) but still the same. 

If there is only one pagy_nav in same page, then it works well.

Controller 
```ruby
@pagy_draft, @draft = pagy(blogs.draft)
@pagy_published, @published = pagy(blogs.published, page_param: :page_published, items: 1)
```

gem 'rails', '5.2.2'
gem 'pagy', '2.1'
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]

**Comment by ddnexus** [comment]
Are you using `pagy_nav` or some other flavor of it? (e.g. compact or responsive)?
Can you paste also the code in the view/template?

**Comment by vshy108** [comment]
I tried switch pagy_nav to pagy_materialize_responsive_nav and pagy_bootstrap_responsive_nav (with editing the pagy.rb initializer content), but the problem still remains.

Below is my view in slim 

```slim
h1 Draft blogs
.table-responsive
  table.table.table-striped.table-sm
    thead.thead-dark
      tr
        th Title
        th Tags
        th Created
        th Modified
        th
        th

    tbody
      - @draft.each do |blog|
        tr
          td = link_to blog.title, blog
          td = blog.tags.join(',').presence || '-'
          td = blog.created_at.strftime('%F %R')
          td = blog.updated_at.strftime('%F %R')
          td = link_to 'Edit', edit_blog_path(blog)
          td = link_to 'Destroy', blog, data: { confirm: 'Are you sure?' }, method: :delete
#draft_cont
  == pagy_nav(@pagy_draft)

br

h1 Published blogs

div.table-responsive
  table.table.table-striped.table-sm
    thead.thead-dark
      tr
        th Title
        th Tags
        th Created
        th Modified
        th
        th

    tbody
      - @published.each do |blog|
        tr
          td = link_to blog.title, blog
          td = blog.tags.join(',').presence || '-'
          td = blog.created_at.strftime('%F %R')
          td = blog.updated_at.strftime('%F %R')
          td = link_to 'Edit', edit_blog_path(blog), method: :get
          td = link_to 'Destroy', blog, data: { confirm: 'Are you sure?' }, method: :delete
#published_cont
  == pagy_nav(@pagy_published)

javascript:
  $(document).on('turbolinks:load', function() {
    Pagy.init(document.getElementById('draft_cont'));
    Pagy.init(document.getElementById('published_cont'));
  });
```

**Comment by vshy108** [comment]
when I switched the pagy_nav to **pagy_bootstrap_compact_nav**

If I type the page number in it's input, it will navigate to 
http://localhost:3000/blogs?page=2&page_published=-pagy-4355296507659834556-
then auto redirect to
http://localhost:3000/blogs?page=2&page_published=2

If I click the next button to page 2,
it will navigate to 
http://localhost:3000/blogs?page=2&page_published=-pagy-4355296507659834556-
and stop

**Comment by ddnexus** [comment]
That's really weird for v2.1. That was happening a while ago, but it has been fixed. Can you check that you don't have any `pagy.js` content anywhere in your app, and you are loading it from the gem?

**Comment by ddnexus** [comment]
And another thing, please, remove any javascript and confirm that even without javascript the simple `pagy_nav` elements still have the problem. Thanks.

**Comment by vshy108** [comment]
I checked and I ensure that I dont have any pagy.js content anywhere in my app. I am loading it by adding` //= require pagy` to app/assets/javascripts/application.js. I also try to remove any javascript and confirm that even without javascript the simple pagy_nav elements still have the problem in my rails project.

**Comment by ddnexus** [comment]
It looks like a bug, not a mis-configuration. I will look into that tomorrow. Thanks.

**Comment by ddnexus** [comment]
Fixed in e9f467a49233a1c31233108a536e9a8a61cc1917 
Hotfix 2.1.1 pushed to rubygem

**Comment by dom-VMS** [comment]
If it means anything, I too had this same issue. Luckily I just found this and updated the gem to 2.1.1. It did the trick! Thanks for putting out the fix in a very timely manner.

**Comment by ddnexus** [comment]
@dom-VMS Thanks for the thanks!
